name: Lint/Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Run image
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1

      - name: Format
        uses: psf/black@c6755bb741b6481d6b3d3bb563c83fa060db96c9 # v26.3.1

      - name: Install dependencies
        run:  |
          poetry install

      - name: Unit Tests
        run:  |
          set -o pipefail
          poetry run pytest --junitxml=pytest.xml --cov=. tests | tee pytest-coverage.txt

      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@26f986d2599c288bb62f623d29c2da98609e9cd4 #v1.6.0
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
